### ISSUE TITLE
Add support for suppressing the currency symbol

### ISSUE THREAD

**Issue by seibar** [bcherny/format-as-currency#10]
First of all, thank you for your work creating this directive!

It would be nice to configure the directive to suppress the currency symbol in case users do not want to see the `$` (or their localized symbol) in the text input.

**Comment by bcherny** [comment]
closed in https://github.com/bcherny/format-as-currency/commit/2d50bea16545d43ccac6a397e0630d3b294f443b

**Comment by bcherny** [comment]
thank you for the contribution, and sorry it took so long to get back to you! there were a few issues with your pr, so rather than go back and forth, i pushed a more general fix in https://github.com/bcherny/format-as-currency/commit/2d50bea16545d43ccac6a397e0630d3b294f443b. you can now pass in any custom filter as a currency formatter, see https://github.com/bcherny/format-as-currency#with-a-custom-curency-formatter.
