### ISSUE TITLE
Custom filter doesn't format input value properly.

### ISSUE THREAD

**Issue by HmzAli** [bcherny/format-as-currency#22]
When I want to use my own currency via currency-filter="myCurrency", the displayed value in the input isn't formatted as expected e.g. USD12222.00, instead of USD12,222.00. 

Here is my filters: 

```
angular.module('app')
    .filter('myCurrency', myCurrency);

function myCurrency() {
    return function (value) {
        return 'USD' + value; 
    };
}
```

and HTML:

`<input type="text" format-as-currency currency-filter="myCurrency" name="fee" ng-model="Nego.fee">
`

**Comment by justinbwarner** [comment]
I ran into the same issue. It looks like formatAsCurrency directive sets the filter using scope.$watch after the value in the model is set, so by the time the filter is there the value has already been formatted. 

I believe the fix in the directive is to set the filter at the very beginning of the link function if attrs.currencyFilter is present. 

In my case I worked around it by setting the value of my scope variable in a $timeout so that it happens after the above $watch is processed. Using your example above, it might look something like:

```
$timeout(function() {
    $scope.Nego.fee = 12222.00;
});
```

**Comment by bcherny** [comment]
Feel free to put up a PR and I'll be sure to take a look. Otherwise, I'll try to get to this soon.

**Comment by danielr18** [comment]
Fix isn't working for me, try typing 122250 for example, it should apply the filter and return something like 122,250.00 but it returns 122250.00

**Comment by bcherny** [comment]
@danielr18 I'm not sure when I can get to this  - in the meantime, PRs with tests are welcome :)

**Comment by danielr18** [comment]
@bcherny What do you think if instead of adding custom filters, we add attributes for currency symbol, group separator and decimal separator (attributes that currency filter accepts) because at the moment, adding a custom filter doesn't apply the currency filter (which is the point of this library)
